-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyDecisionCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastDailyReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastMonthlyReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "monthlyDecisionCount" INTEGER NOT NULL DEFAULT 0;
